apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: your-dockerhub-username/mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: yourpassword
          ports:
            - containerPort: 3306
